### ISSUE TITLE
Post fails

### ISSUE THREAD

**Issue by dovy** [iamale/arequests#1]
Love what you've done here, but post isn't working. Any ideas?

**Comment by dovy** [comment]
Post is the ONLY type that won't pass properly through. Tested patch, put, etc. Example call:

```
res = w.businesses['0fc74470-d569-4bb6-a9dc-35f13c1a92c1'].invoices.post(data={})
```

**Comment by iamale** [comment]
Hi Dovy, thanks for taking time to report this! I will take a look tonight.

**Comment by dovy** [comment]
Thank you. I am very confused by it. I've tried tracking it down, but I can't locate why.

**Comment by iamale** [comment]
@dovy Sorry, I still can't reproduce it. If you're still interested, would you mind sharing a few more details (in private, if you want)?

**Comment by dovy** [comment]
@iamale I think private would be best. You can email me@dovy.io. I could send you example code tonight.

**Comment by iamale** [comment]
Sent an email to you!
